backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "industries"
    label: "Industries"
    files:
      - file: "src/pages/data/industry/index.md"
        label: "Industry"
        name: "industry"
        fields:
          - {label: Add Industry, name: addinn, widget: list, fields: [{label: Industry Name, name: inn, widget: string}]}
